'use client';
import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import Link from 'next/link';
import * as Dialog from '@radix-ui/react-dialog';
import { ArrowRight, ArrowUpRight, Check, Download, FileText, LockKeyhole, Menu, Search, ShieldCheck, X, BookOpen, Plus } from 'lucide-react';
import initialCourses from '../data/courses.json';
import initialPlans from '../config/plans.json';
import { api, type Course, type Plan, type User } from '../lib/types';

const practiceFormats:Record<string,string>={mock:'Short mock exams · Answer guidance included',project:'Project and report practice',reflection:'Reflective learning practice',lab:'Lab preparation practice',seminar:'Seminar analysis practice','topic-template':'Offering-specific topic · In preparation'};
const supportEmail=process.env.NEXT_PUBLIC_SUPPORT_EMAIL;
const disclaimer='EazyGrades is not affiliated with, endorsed by, or officially connected to Concordia University or any school or testing organization.';
const faq=[
 ['What do I get with a practice set?','Each available course includes exactly two downloadable PDFs: Core Exam Practice for fundamental concepts and Advanced Exam Practice for more demanding applications. Both contain AI-generated exam-style practice questions for study purposes only.'],
 ['Which courses and formats are covered?','The collection focuses on COMP and SOEN, alongside ENGR courses from the linked undergraduate calendar. Standard sets are short mocks with two multipart questions and answer guidance per PDF, covering selected topics. Projects, labs, seminars and reflective courses use labelled practice exercises. Rotating-topic courses have templates in preparation until the offering syllabus is available.'],
 ['Are these real past exams?','No. These PDFs are AI-generated educational practice material. They are not real past exams, official exam questions, or material supplied by a professor.'],
 ['Will the questions match my exam?','Course codes help you find relevant subject areas. Content may differ from your current course outline and can contain errors. Compare it with your syllabus and verify solutions using trusted course resources. No grade, passing result, or exam outcome is guaranteed.'],
 ['How do I download my PDFs?','Once your payment is confirmed, sign in, find your course, and select View Practice Set. You can download both PDFs while a plan covering that course is active. Downloads are for your personal study use only.'],
 ['How do the plans renew?','Basic and Pro renew monthly. The Semester Plan renews every four months. You can manage your subscription in the Stripe billing portal from your account. Your checkout displays the billing terms before payment.'],
 ['Can I share a practice PDF?','No. Your access is personal. Copying for distribution, resale, redistribution, or publicly sharing purchased PDFs is not permitted.'],
 ['Can I request a refund?','Digital sales are generally final after access or download is provided, subject to applicable consumer rights. Duplicate charges, access issues caused by EazyGrades, and wrong product delivery may qualify for review. See the Refund Policy for details.']
];
const legal:Record<string,{title:string;intro:string;sections:[string,string][]}>={
 privacy:{title:'Privacy Policy',intro:'We collect the information needed to provide your account, process purchases, and deliver your practice material.',sections:[
 ['Information we collect','We may collect your name, email address, account details, purchase and subscription records, and messages you send to support. Passwords are stored as salted hashes. We collect only information necessary to provide and protect the service.'],
 ['Payments','Payments are processed by Stripe. EazyGrades stores payment references and subscription status to manage access. We do not collect or store full card details. Stripe processes payment information under its own privacy policy.'],
 ['Cookies and analytics','We use an essential session cookie to keep you signed in. Cookies or analytics may be used to understand usage and improve the service; nonessential tools will be disclosed and consent requested where required. No optional analytics are currently installed.'],
 ['How information is used and shared','Information is used to deliver purchases, secure accounts, provide support, and meet applicable obligations. We do not sell user data. Service providers receive only information needed to perform their functions.'],
 ['Retention and your choices','We retain information as needed to provide the service and meet applicable recordkeeping obligations. Contact support to request access, correction, or deletion of your information. Some transaction records may need to be retained.'],
 ['Privacy questions','Use the Contact link below for privacy questions or requests concerning your account.']
 ]},
 terms:{title:'Terms & Conditions',intro:'By using EazyGrades, you agree to these terms. Please read them before subscribing or downloading a practice set.',sections:[
 ['Educational practice only','EazyGrades provides AI-generated exam-style practice PDFs for educational study and revision only. Content may contain errors and should be checked against trusted learning resources. It is not official course material, real past exams, or professor-provided exam questions.'],
 ['No affiliation or guaranteed results',`${disclaimer} No grade, passing result, admission, or other academic outcome is guaranteed.`],
 ['Personal use licence','Purchased PDFs are licensed for your personal study use only. You may not resell, redistribute, publicly share, or copy the PDFs for distribution. Keep your account credentials private and use the content in accordance with your institution’s academic rules.'],
 ['Plans and access','Basic covers one selected course. Pro and the Semester Plan cover all available courses. Basic and Pro bill monthly; the Semester Plan bills every four months. Plans renew until canceled. Downloads require an active, paid subscription covering that course. Cancellation takes effect at the end of the paid billing period when selected in the billing portal.'],
 ['Changes to the service','We may update content, pricing, or access rules. Material changes affecting existing subscriptions will be communicated as required, and applicable price changes disclosed before renewal. A course listing marked In preparation is not currently available for purchase.'],
 ['Misuse and suspension','Misuse, unauthorized sharing, payment disputes, or abuse of the service may lead to account suspension or restricted access. Contact support if you believe access was restricted in error.'],
 ['Your rights','These terms do not exclude any rights or remedies that cannot be excluded under applicable consumer law. For digital purchase concerns, please read the Refund Policy and contact support.']
 ]},
 refund:{title:'Refund Policy',intro:'EazyGrades sells digital practice PDFs. There are no physical products or shipping charges.',sections:[
 ['Digital purchases','Sales are generally final once access or a download is provided, subject to any rights you have under applicable consumer law. Please review course availability, the selected plan, and its billing period before purchasing.'],
 ['When we may consider a refund','We may consider refunds for duplicate charges, technical access issues caused by EazyGrades that cannot be resolved, or delivery of the wrong product. Requests are reviewed case by case.'],
 ['How to request a review','Contact support with your account email, purchase date, and a description of the issue. Include a receipt reference if available. Never send full card details or your password.'],
 ['Refund processing','Approved refunds are returned to the original payment method. Processing time depends on the payment provider and your bank. Access associated with a refunded purchase may be removed.'],
 ['Subscription cancellation','Canceling a subscription stops future renewals according to the billing portal’s displayed terms. It does not automatically refund a completed charge. You can request review of a charge under the circumstances described above.']
 ]}
};
function Logo(){return <Link className="logo" href="/" aria-label="EazyGrades home"><span className="logo-mark" aria-hidden="true"><i/><i/><i/></span>Eazy<span>Grades</span><span className="logo-dot">.</span></Link>;}
function Modal({open,onOpenChange,title,description,children}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;description:string;children:ReactNode}){return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="modal-overlay"/><Dialog.Content className="modal"><Dialog.Title>{title}</Dialog.Title><Dialog.Description className="modal-description">{description}</Dialog.Description><Dialog.Close className="icon-button close" aria-label="Close dialog"><X size={20}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;}
function Price({plan}:{plan:Plan}){return <div className="price"><span>{new Intl.NumberFormat('en-CA',{style:'currency',currency:plan.currency,maximumFractionDigits:0}).format(plan.amount/100)}</span><span> CAD / {plan.period}</span></div>;}

export default function Store({page}:{page:string}){
 useEffect(()=>{
  // Start each page at the top, while preserving intentional anchor links.
  if(!window.location.hash)window.scrollTo({top:0,left:0,behavior:'instant'});
 },[page]);
 const [courses,setCourses]=useState<Course[]>(initialCourses);
 const [plans,setPlans]=useState<Plan[]>(initialPlans);
 const [user,setUser]=useState<User|null>(null);
 const [loaded,setLoaded]=useState(false);
 const [serviceError,setServiceError]=useState('');
 const [menu,setMenu]=useState(false);
 const [authOpen,setAuthOpen]=useState(false);
 const [register,setRegister]=useState(false);
 const [selected,setSelected]=useState<Course|null>(null);
 const [contact,setContact]=useState(false);
 const [search,setSearch]=useState('');
 const [category,setCategory]=useState('All courses');
 const [basicCourse,setBasicCourse]=useState('');
 const [busy,setBusy]=useState('');
 const [error,setError]=useState('');
 const [checkoutMessage,setCheckoutMessage]=useState('');
 const [reload,setReload]=useState(0);
 useEffect(()=>{
  let live=true;
  setLoaded(false);setServiceError('');
  Promise.all([api<{courses:Course[];plans:Plan[]}>('/catalog'),api<{user:User|null}>('/me')]).then(([catalog,account])=>{if(live){setCourses(catalog.courses);setPlans(catalog.plans);setUser(account.user);}}).catch(e=>{if(live)setServiceError(e.message);}).finally(()=>{if(live)setLoaded(true);});
  return()=>{live=false;};
 },[reload]);
 useEffect(()=>{
  const params=new URLSearchParams(window.location.search);
  if(params.get('checkout')==='cancelled'){setCheckoutMessage('Checkout canceled. No access has been activated. You can choose a plan when you’re ready.');return;}
  if(params.get('checkout')!=='success')return;
  if(!user){setCheckoutMessage('Sign in to confirm your payment and access your PDFs.');return;}
  const session=params.get('session_id');if(!session)return;
  let stopped=false;let timer:ReturnType<typeof setTimeout>;let count=0;
  const check=async()=>{try{const result=await api<{status:string;user:User}>(`/billing/status/${encodeURIComponent(session)}`);if(stopped)return;if(result.status==='confirmed'){setUser(result.user);setCheckoutMessage('Payment confirmed. Your practice PDFs are ready in Courses.');return;}if(['failed','expired','unpaid','past_due','canceled','incomplete_expired'].includes(result.status)){setCheckoutMessage('Payment was not confirmed or checkout expired. Check your account or contact support before trying again.');return;}setCheckoutMessage(count<10?'Confirming your payment securely. Access will appear after payment confirmation.':'Confirmation is taking longer than expected. Refresh this page shortly or contact support.');if(++count<11)timer=setTimeout(check,3000);}catch(e){if(!stopped)setCheckoutMessage((e as Error).message);}};
  check();return()=>{stopped=true;clearTimeout(timer);};
 },[user?.email,reload]);
 async function authenticate(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy('auth');setError('');const data=new FormData(event.currentTarget);try{const result=await api<{user:User}>(register?'/auth/register':'/auth/login',{email:data.get('email'),password:data.get('password'),...(register?{name:data.get('name')}:{})});setUser(result.user);setAuthOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function checkout(plan:Plan){setError('');if(!user){setAuthOpen(true);return;}setBusy(plan.id);try{const result=await api<{url:string}>('/billing/checkout',{planId:plan.id,...(plan.scope==='selected'?{courseId:basicCourse}:{})});window.location.assign(result.url);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function billing(){setBusy('portal');setError('');try{const result=await api<{url:string}>('/billing/portal',{});window.location.assign(result.url);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 async function download(course:Course,product:string){setBusy(product);setError('');try{const response=await fetch(`/api/download/${encodeURIComponent(course.id)}/${encodeURIComponent(product)}`,{cache:'no-store'});if(!response.ok){const result=await response.json();throw Error(result.error||'Download unavailable.');}const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`EazyGrades-${course.code.replace(' ','-')}-${product}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy('');}}
 const filtered=courses.filter(c=>(category==='All courses'||c.category===category)&&`${c.code} ${c.title}`.toLowerCase().includes(search.trim().toLowerCase()));
 function courseCard(c:Course){return <article className="course-card" key={c.id}><div className="card-top"><span className="course-code">{c.code}</span><span className="tiny-label">{c.available?'AVAILABLE':'IN PREPARATION'}</span></div><h3>{c.title}</h3><p>{c.description}</p><small className="practice-format">{practiceFormats[c.practiceKind||'mock']}</small><div className="course-includes"><span><FileText size={15}/>2 AI-generated practice PDFs</span><small>Core Practice Set <span>·</span> Advanced Practice Set</small></div><button className="card-link" onClick={()=>{setSelected(c);setError('');}}>View Practice Set <ArrowUpRight size={18}/><span className="sr-only"> for {c.code}</span></button></article>;}
 function pricingCards(){return <div className="pricing-grid">{plans.map(plan=><article className={`plan-card ${plan.id==='pro'?'featured':''}`} key={plan.id}>{plan.id==='pro'&&<div className="plan-ribbon">THE COMPLETE COLLECTION</div>}<span className="eyebrow">{plan.id==='semester'?'A TERM AT A TIME':plan.id==='pro'?'ROOM TO GO FURTHER':'ONE COURSE. FULL FOCUS.'}</span><h2>{plan.name}</h2><p>{plan.description}</p><Price plan={plan}/><div className="plan-divider"/><ul>{plan.features.map(f=><li key={f}><Check size={17}/>{f}</li>)}</ul>{plan.scope==='selected'&&<label className="course-select">Your course<select value={basicCourse} onChange={e=>setBasicCourse(e.target.value)} disabled={!courses.some(c=>c.available)}><option value="">{courses.some(c=>c.available)?'Select a course':'Courses in preparation'}</option>{courses.filter(c=>c.available).map(c=><option key={c.id} value={c.id}>{c.code} — {c.title}</option>)}</select></label>}<button className={`button ${plan.id==='pro'?'primary':'secondary'}`} disabled={!loaded||!plan.checkoutEnabled||Boolean(busy)||(plan.scope==='selected'&&!basicCourse)} onClick={()=>checkout(plan)}>{busy===plan.id?'Opening checkout…':!loaded?'Checking availability…':!plan.checkoutEnabled?'Available at launch':`Choose ${plan.name}`}<ArrowRight size={17}/></button><small className="renewal">Renews every {plan.period==='month'?'month':plan.period}. CAD.</small></article>)}</div>;}
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <header className="header"><div className="container header-inner"><Logo/><nav aria-label="Main navigation" className={menu?'main-nav open':'main-nav'}>{[['home','Home'],['courses','Courses'],['pricing','Pricing'],['faq','FAQ']].map(([key,label])=><Link key={key} href={key==='home'?'/':`/${key}`} aria-current={page===key?'page':undefined} onClick={()=>setMenu(false)}>{label}</Link>)}</nav><button className="signin" disabled={!loaded} onClick={()=>{setAuthOpen(true);setError('');}}>{user?'My account':'Sign in'}<ArrowUpRight size={15}/></button><button className="icon-button menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <main id="main">
 {serviceError&&<div className="container"><div className="notice error" role="alert">{serviceError}<button onClick={()=>setReload(reload+1)}>Try again</button></div></div>}
 {page==='home'&&<>
 <section className="hero container"><div className="hero-copy"><div className="eyebrow hero-label"><span className="status-dot"/>LESS SEARCHING. MORE PRACTICE.</div><h1>3 days left?<br/>You’re in the<br/><span>right place.</span></h1><p className="hero-description">Focused computer science and software engineering practice, with engineering core courses included.</p><p className="hero-detail">AI-generated exam-style PDFs. Core and Advanced practice for your next study session.</p><div className="hero-actions"><Link className="button primary" href="/courses">Browse Courses<ArrowRight size={18}/></Link><Link className="button secondary" href="/pricing">View Plans</Link></div><div className="hero-footnote"><ShieldCheck size={16}/>For study and revision only. Not official course material.</div></div>
 <div className="hero-visual" role="img" aria-label="Illustration of the two practice PDF formats"><div className="visual-orbit"/><div className="paper paper-back"><div className="paper-brand">EAZYGRADES<span>02 / ADVANCED</span></div><div className="paper-rule"/><div className="paper-code">COMP 232</div><h2>Advanced<br/>Exam Practice</h2><p>Extend your understanding.</p><div className="paper-lines"><i/><i/><i/></div></div><div className="paper paper-front"><div className="paper-brand">EAZYGRADES<span>01 / CORE</span></div><div className="paper-rule"/><div className="paper-code">COMP 232</div><h2>Core Exam<br/>Practice</h2><p>Mathematics for Computer Science</p><div className="paper-question"><span>01 / MATHEMATICAL REASONING</span><div>Build the argument.<br/>Show your working.</div><i/><i/></div><div className="paper-bottom"><span>AI-GENERATED PRACTICE</span><FileText size={15}/></div></div><div className="pdf-caption"><span className="pdf-icon"><FileText size={20}/></span><div>Two sets. A focused session.<small>Core + Advanced · PDF format</small></div><Check size={18}/></div><span className="preview-label">FORMAT PREVIEW · NOT A PRODUCT SAMPLE</span></div>
 </section>
 <div className="benefit-strip"><div className="container benefit-inner"><span><BookOpen size={19}/>Course-focused practice</span><span><FileText size={19}/>2 PDFs per course</span><span><Download size={19}/>Download. Work at your pace.</span><span><LockKeyhole size={19}/>Secure checkout with Stripe</span></div></div>
 <section className="container section"><div className="section-heading"><div><p className="eyebrow">START WITH YOUR COURSE</p><h2>A little structure.<br/>A lot more focus.</h2></div><div className="section-aside"><p>Start with COMP and SOEN courses.<br/>Explore engineering core practice too.</p><Link className="text-link" href="/courses">Explore courses<ArrowRight size={17}/></Link></div></div><div className="course-grid">{courses.slice(0,3).map(courseCard)}</div>{!courses.some(c=>c.available)&&<p className="subtle-note">Our first practice sets are in preparation. Downloads will open after content review.</p>}</section>
 <section className="method-section"><div className="container method-grid"><div><p className="eyebrow">A SIMPLE WAY TO STUDY</p><h2>Less setup.<br/>More working <br/>things out.</h2><p className="muted">Designed for focused practice before exams.</p></div><div className="steps">{[['01','Find your course','Browse by course code and check the subject coverage.'],['02','Choose your access','Pick a plan that fits the courses you’re studying.'],['03','Make time for practice','Download Core and Advanced PDFs. Work through them at your own pace.']].map(([n,t,d])=><div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight size={19}/></div>)}</div></div></section>
 <section className="container closing"><div><p className="eyebrow">YOUR NEXT STUDY SESSION</p><h2>Start with a clear plan.</h2><p>Simple access. Focused material. Space to do the work.</p></div><Link className="button primary" href="/pricing">Find your plan<ArrowRight size={18}/></Link></section>
 </>}
 {page==='courses'&&<section className="container page-section"><div className="page-heading"><p className="eyebrow">THE PRACTICE COLLECTION</p><h1>Find your course.<br/><span>Focus your practice.</span></h1><p>Computer science and software engineering first, with engineering core courses included.<br/>Two AI-generated practice PDFs per course. Check the format and covered topics before choosing.</p></div><div className="catalog-toolbar"><label className="search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search course code or name" aria-label="Search course code or name"/></label><span>{filtered.length} courses</span></div><div className="filters" aria-label="Filter by category">{['All courses',...new Set(courses.map(c=>c.category))].map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>{!courses.some(c=>c.available)&&<div className="catalog-note"><span className="status-dot"/>First collection in preparation. Review each set’s availability before choosing a plan.</div>}{filtered.length?<div className="course-grid">{filtered.map(courseCard)}</div>:<div className="empty"><Search size={30}/><h2>No courses found.</h2><p>Try a different code or clear the filters.</p><button className="button secondary" onClick={()=>{setSearch('');setCategory('All courses');}}>Clear filters</button></div>}<div className="catalog-bottom"><ShieldCheck size={20}/><p>Independent AI-generated educational practice material. Check topic coverage against your syllabus. No official questions or past exams.</p></div></section>}
 {page==='pricing'&&<section className="container page-section"><div className="page-heading centered"><p className="eyebrow">SIMPLE PLANS. FOCUSED PRACTICE.</p><h1>Your courses.<br/><span>Your pace.</span></h1><p>Choose the access that fits your study session.<br/>Every available course includes Core and Advanced practice PDFs.</p></div>{checkoutMessage&&<div className="notice" role="status">{checkoutMessage}<Link href="/courses">Browse Courses<ArrowRight size={16}/></Link></div>}{error&&!authOpen&&<div className="notice error" role="alert">{error}</div>}{pricingCards()}<div className="pricing-notes"><span><LockKeyhole size={17}/>Payments handled securely by Stripe</span><span><FileText size={17}/>Digital downloads. Personal study use.</span></div><p className="pricing-disclosure">All prices are in Canadian dollars. Plans renew automatically at the period shown. Manage billing from your account. {!plans.some(p=>p.checkoutEnabled)&&'Checkout is not open yet. Practice sets and payment access are being prepared.'}</p><div className="pricing-help"><h2>Not sure where to start?</h2><p>Check the course collection first, then choose the access you need.</p><Link className="text-link" href="/courses">Browse Courses<ArrowRight size={17}/></Link></div></section>}
 {page==='faq'&&<section className="container page-section faq-page"><div className="page-heading"><p className="eyebrow">A FEW THINGS TO KNOW</p><h1>Good questions.<br/><span>Clear answers.</span></h1><p>What’s included, how access works, and what to expect.</p></div><div className="faq-list">{faq.map(([q,a])=><details key={q}><summary>{q}<Plus size={20}/></summary><p>{a}</p></details>)}</div><div className="help-line"><p>Still have a question?</p><button className="text-link" onClick={()=>setContact(true)}>Contact support<ArrowUpRight size={17}/></button></div></section>}
 {legal[page]&&<section className="container page-section legal-page"><div className="page-heading"><p className="eyebrow">EAZYGRADES / POLICIES</p><h1>{legal[page].title}</h1><p>{legal[page].intro}</p><span className="updated">Last updated: September 12, 2026</span></div>{legal[page].sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}<button className="text-link" onClick={()=>setContact(true)}>Contact support<ArrowUpRight size={17}/></button></section>}
 </main>
 <footer className="footer"><div className="container"><div className="footer-top"><div><Logo/><p>Good practice starts with focus.</p></div><div className="footer-links"><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms & Conditions</Link><Link href="/refund">Refund Policy</Link><button onClick={()=>setContact(true)}>Contact<ArrowUpRight size={14}/></button></div></div><div className="footer-bottom"><p>© 2026 EazyGrades. For personal study use only.</p><p>{disclaimer}<br/>AI-generated educational practice material. No academic results are guaranteed.</p></div></div></footer>
 <Modal open={authOpen} onOpenChange={v=>{setAuthOpen(v);setError('');}} title={user?'Your account':register?'Create your account':'Welcome back.'} description={user?'Manage your practice access and billing.':'Sign in to access your purchased practice PDFs.'}>
 {user?<><p className="account-email">{user.email}</p>{user.subscriptions.length?user.subscriptions.map((s,i)=><div className="account-plan" key={i}><strong>{plans.find(p=>p.id===s.planId)?.name}</strong><p>{s.blocked?'Access under review':s.status==='active'&&s.expiresAt<=Date.now()?'expired':s.status}{s.courseId?` · ${s.courseId.toUpperCase().replace('-',' ')}`:''}</p><small>{s.cancelAtPeriodEnd?'Access ends':'Current period ends'} {new Date(s.expiresAt).toLocaleDateString()}</small></div>):<p className="muted">You don’t have an active plan yet.</p>}<Link className="button primary" href="/courses" onClick={()=>setAuthOpen(false)}>Browse your courses<ArrowRight size={17}/></Link>{user.hasBilling&&<button className="button secondary" disabled={Boolean(busy)} onClick={billing}>{busy==='portal'?'Opening…':'Manage billing'}</button>}<button className="text-link" disabled={Boolean(busy)} onClick={async()=>{setBusy('logout');try{await api('/auth/logout',{});setUser(null);setAuthOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy('');}}}>Sign out</button></>:<form className="auth-form" onSubmit={authenticate}>{register&&<label>Name<input name="name" autoComplete="name" required maxLength={80}/></label>}<label>Email<input name="email" type="email" autoComplete="email" required maxLength={254}/></label><label>Password<input name="password" type="password" autoComplete={register?'new-password':'current-password'} minLength={10} maxLength={128} required/></label>{register&&<><small>Use at least 10 characters.</small><p className="form-terms">By creating an account, you agree to the <Link href="/terms">Terms & Conditions</Link> and acknowledge the <Link href="/privacy">Privacy Policy</Link>.</p></>}<button className="button primary" disabled={Boolean(busy)}>{busy==='auth'?'Please wait…':register?'Create account':'Sign in'}<ArrowRight size={17}/></button><button type="button" className="text-link" onClick={()=>{setRegister(!register);setError('');}}>{register?'Already have an account? Sign in':'New here? Create an account'}</button><button type="button" className="muted-link" onClick={()=>{setAuthOpen(false);setContact(true);}}>Need help signing in?</button></form>}{error&&<p className="form-error" role="alert">{error}</p>}
 </Modal>
 <Modal open={Boolean(selected)} onOpenChange={v=>{if(!v)setSelected(null);}} title={selected?`${selected.code} · ${selected.title}`:''} description="2 AI-generated practice PDFs. For study and revision only.">
 {selected&&<><p className="muted">{selected.description}</p><p className="small-print">{selected.coverageNote}</p>{selected.sourceUrl&&<a className="text-link" href={selected.sourceUrl} target="_blank" rel="noopener noreferrer">Course calendar description<ArrowUpRight size={15}/></a>}<div className="product-list">{selected.products.map((p,i)=><div className="product-row" key={p.id}><span className="product-number">0{i+1}</span><div><h3>{p.title}</h3><p>AI-generated exam-style practice questions for study purposes only.</p>{user?.accessibleCourseIds.includes(selected.id)&&<button className="text-link" disabled={Boolean(busy)} onClick={()=>download(selected,p.id)}>{busy===p.id?'Preparing download…':'Download PDF'}<Download size={16}/></button>}</div><FileText size={22}/></div>)}</div>{!selected.available?<div className="notice">{selected.practiceKind==='topic-template'?'Offering-specific topic. The current syllabus is needed to complete these practice sets. Downloads are not available yet.':'In preparation. This set is not available for purchase or download yet.'}</div>:!user?.accessibleCourseIds.includes(selected.id)&&<Link className="button primary" href="/pricing" onClick={()=>setSelected(null)}>View Plans<ArrowRight size={17}/></Link>}<p className="small-print">Not official course material. Compare the covered topics with your current syllabus. No exam result is guaranteed.</p>{error&&<p className="form-error" role="alert">{error}</p>}</>}
 </Modal>
 <Modal open={contact} onOpenChange={setContact} title="Contact EazyGrades" description="Questions about access, billing, or privacy?">
 {supportEmail?<><p className="muted">Include your account email and a short description of the issue. Please don’t send passwords or card details.</p><a className="button primary" href={`mailto:${supportEmail}`}>Email support<ArrowUpRight size={17}/></a><p className="small-print">{supportEmail}</p></>:<div className="notice">Support contact details will be available before checkout opens. Payment access is still being prepared.</div>}
 </Modal>
 </>;
}
